### ISSUE TITLE
How was this generated? Some items/descriptions seem off/wrong...

### ISSUE THREAD

**Issue by idrmhyprbls** [hayatbiralem/eco.json#1]
Hi, nice list, but I just played this pretty common game:

https://www.365chess.com/eco/C78_Ruy_Lopez_Archangelsk_(counterthrust)_variation

and the very first thing I looked up doesn't seem to be correct so I have to question the whole thing:

https://www.365chess.com/eco/C77_Ruy_Lopez_Morphy_defence

Your DB has this position listed as C78, and extending into move 5. (the Main line). This entry should have a title "Roy Lopez: Morphy Defense, 5. 0-0", and there should be an entry for just "Roy Lopez: Morphy Defense" for C77 ending just after move 4. So the flow is C00->C20->C60->C70->C77->C78. No? 

Can't be the only one.

**Comment by JeffML** [comment]
linking #3

**Comment by JeffML** [comment]
Completed by #3
