### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by PedanticHacker** [hayatbiralem/eco.json#10]
In `README.md`, there's a typo where the `fen` field is described. Its description is:

fen

> The Forsythe-Edwards Notation of the position on the board after all opening moves are played. FEN notations uniquely identify each opening.

The meaning of the FEN acronym is not `Forsythe-Edwards Notation`, but it is `Forsyth-Edwards Notation`, so without the `e` in `Forsythe`. This Wikipedia article proves it: https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation

Would you be so kind as to fix the typo from `Forsythe` to `Forsyth`? Thank you.

**Comment by JeffML** [comment]
Thanks for catching that. It is now corrected.
