### ISSUE TITLE
I can maintain this if you wish

### ISSUE THREAD

**Issue by JeffML** [hayatbiralem/eco.json#2]
I've been using  JSON opening data generated from SCID on my own project, but need more recent data. While I have no problem using the same ECO data you used, I don't feel that github needs yet another JSON opening database. I'd prefer to update this one, adding FEN data as well. What say you?

**Comment by hayatbiralem** [comment]
Hey, sure. That would be cool. Thank you.

**Comment by hayatbiralem** [comment]
I added you as a contributor to this repo. Thanks in advance.
