### ISSUE TITLE
Code and move sequence not aligned with attributed eco project

### ISSUE THREAD

**Issue by JeffML** [hayatbiralem/eco.json#3]
I'm finding a lot of mismatched ECO codes and move sequences from that in the .tsv files at [eco](https://github.com/niklasf/eco).  See attached.

[stderr.log](https://github.com/hayatbiralem/eco.json/files/11739943/stderr.log)

**Comment by hayatbiralem** [comment]
Maybe we may ask for a JSON version from the more active repo https://github.com/lichess-org/chess-openings. If they can provide a JSON file in their repo we can archive this one.

**Comment by JeffML** [comment]
I've done that already. There are variations in this project that are not
in the lichess TSVs. Also, there is the older SCID project that I want to
analyze.

I can hand over the JSON to lichen, with/without the merged* eco.js and
SCID data.

*merged, but source identified in the JSON (tsv/js/scid)

**Comment by JeffML** [comment]
Closing as completed

**Comment by JeffML** [comment]
Closing as completed
